---
- name: lab06 - cv_facts lab
  hosts: CloudVision
  connection: local
  gather_facts: no

  tasks:
    - name: "Gather CVP facts from {{inventory_hostname}}"
      arista.cvp.cv_facts:
        facts:
          - tasks
      register: CVP_FACTS

    - name: 'Display pending tasks from {{inventory_hostname}}'
      debug:
        msg: '{{CVP_FACTS.ansible_facts.tasks}}'

    - name: 'Execute all pending tasks and wait for completion for 60 seconds'
      arista.cvp.cv_task:
        tasks: "{{ CVP_FACTS.ansible_facts.tasks }}"
        wait: 60