---
CVP_CONFIGLETS:
  TEAM01-alias: "alias a{{ 999 | random }} show version"
  TEAM01-another-configlet: "alias a{{ 999 | random }} show version"

CVP_CONTAINERS:
  TEAM01:
    parent_container: Tenant
  TEAM01_DC:
    parent_container: TEAM01
  TEAM01_LEAFS:
    parent_container: TEAM01_DC
  TEAM01_SPINES:
    parent_container: TEAM01_DC
