---
- name: Build lab05 on CloudVision
  hosts: CloudVision
  gather_facts: no
  tasks:
    - name: Load local variables from file
      include_vars:
        file: lab_definitions/lab05.yml

    - name: 'Collecting facts from CVP {{inventory_hostname}}.'
      arista.cvp.cv_facts:
      register: CVP_FACTS

    - name: "Configure devices on {{inventory_hostname}}"
      arista.cvp.cv_device:
        devices: "{{CVP_DEVICES}}"
        cvp_facts: '{{CVP_FACTS.ansible_facts}}'
        device_filter: ['TEAM']
        state: absent
      register: CVP_DEVICES_RESULTS

    - name: "Execute pending tasks on {{inventory_hostname}}"
      arista.cvp.cv_task:
        tasks: "{{ CVP_DEVICES_RESULTS.data.tasks }}"
        wait: 720
