---
CVP_CONFIGLETS:
  STUDENT_DEVICE-alias: "alias a{{ 999 | random }} show version"
  STUDENT_DEVICE-another-configlet: "alias a{{ 999 | random }} show version"

CVP_CONTAINERS:
  STUDENT:
    parent_container: Tenant
  STUDENT_DC:
    parent_container: STUDENT
    configlets:
      - 'GLOBAL-ALIASES'
  STUDENT_LEAFS:
    parent_container: STUDENT_DC
  STUDENT_SPINES:
    parent_container: STUDENT_DC
