{
    "ethernet_interfaces": [
        {
            "name": "Ethernet1",
            "peer": "DC1-SPINE1",
            "peer_interface": "Ethernet1",
            "peer_type": "spine",
            "description": "P2P_LINK_TO_DC1-SPINE1_Ethernet1",
            "mtu": 1500,
            "type": "routed",
            "ip_address": "172.31.255.1/31"
        },
        {
            "name": "Ethernet2",
            "peer": "DC1-SPINE2",
            "peer_interface": "Ethernet1",
            "peer_type": "spine",
            "description": "P2P_LINK_TO_DC1-SPINE2_Ethernet1",
            "mtu": 1500,
            "type": "routed",
            "ip_address": "172.31.255.3/31"
        }
    ]
}